# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 5.0 branch
on:
  push:
    branches: [ 5.0 ]
  pull_request:
    branches: [ 5.0 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2                                                                      
                                                                                                       
      # Runs a single command using the runners shell                                                  
      - name: Run a one-line script                                                                    
        run: echo Hello, world!                                                                        
                                                                                                       
      - name: test                                                                                     
        run: ls -lah && docker --help && pwd && ls -lah

      - name: Build something
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          set +e && \
          mkdir -p ~/.docker/cli-plugins/ && \
          curl -L https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx && \
          docker pull -q multiarch/qemu-user-static:latest && \
          docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes --credential yes && \
          docker buildx create --name builder-${GITHUB_SHA::8} --driver docker-container --use && \
          docker buildx inspect --bootstrap && \
          docker info && \
          docker buildx inspect && \
          docker buildx build --platform linux/amd64 --output "type=image,push=false" --cache-to "type=local,dest=/tmp/cache" --tag zabbux/zabbbix-agent:latest --file ./agent/alpine/Dockerfile ./agent/alpine
