# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 5.0 branch
on:
  push:
    branches:
      - trunk
      - dotneft-patch-1
  pull_request:
    branches:
      - trunk   

jobs:
  build:
    strategy:
      fail-fast: false  
      matrix:
        build: 
          - agent
          - agent2
          - java-gateway
          - proxy-mysql
          - proxy-sqlite3
          - server-mysql
          - server-pgsql
          - snmptraps
          - web-apache-mysql
          - web-apache-pgsql
          - web-nginx-mysql
          - web-nginx-pgsql
        os:
         - alpine
         - ubuntu
         - centos
        exclude:
          - os: centos
            build: agent2
          - os: ubuntu
            build: agent2


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                                      

      - name: Install buildx
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          BUILDX_VERSION="0.4.2"
          QEMU_TAG="latest"
          mkdir -p ~/.docker/cli-plugins/ && \
          curl -L https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx && \
          chmod +x ~/.docker/cli-plugins/docker-buildx && \
          docker pull -q multiarch/qemu-user-static:latest && \
          docker run --rm --privileged multiarch/qemu-user-static:${QEMU_TAG} --reset -p yes --credential yes && \
          docker buildx create --name builder-${GITHUB_SHA::8} --driver docker-container --use && \
          docker buildx inspect --bootstrap && \
          docker info && \
          docker buildx inspect
      
      - name: Available platforms
        run: docker buildx inspect | grep Platforms
      
      - name: Prepare environment
        id: prepare_env
        run: |
          DOCKER_PLATFORM="linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le"

          if [ "${{ matrix.os }}" == "ubuntu" ]; then
            DOCKER_PLATFORM="linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le"
          fi

          if [ "${{ matrix.os }}" == "centos" ]; then
            DOCKER_PLATFORM="linux/amd64,linux/arm64,linux/ppc64le"
          fi
          
          if [ "${{ matrix.build }}" == "java-gateway" ]; then
            DOCKER_PLATFORM=${DOCKER_PLATFORM%",linux/ppc64le"}
          fi
          
          IMAGE_TAG_VERSION="${{ matrix.os }}-trunk-test"
          IMAGE_NAME="zabbix/zabbix-${{ matrix.build }}"

          echo ::set-output name=image_name::${IMAGE_NAME}
          echo ::set-output name=image_tag_version::${IMAGE_VERSION}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORM} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --tag $IMAGE_NAME:$IMAGE_TAG_VERSION \
            --file ./${{ matrix.build }}/${{ matrix.os }}/Dockerfile ./${{ matrix.build }}/${{ matrix.os }}

      - name: Build images
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |          
          docker buildx build --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=false" \
            ${{ steps.prepare_env.outputs.buildx_args }}

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker buildx build --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=image,push=true" \
            ${{ steps.prepare_env.outputs.buildx_args }}

      - name: Inspect images
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker buildx imagetools inspect ${{ steps.prepare_env.outputs.image_name }}:${{ steps.prepare_env.outputs.image_tag_version }}
