# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 5.0 branch
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                                      

      - name: Install buildx
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          mkdir -p ~/.docker/cli-plugins/ && \
          curl -L https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx && \
          chmod +x ~/.docker/cli-plugins/docker-buildx && \
          docker pull -q multiarch/qemu-user-static:latest && \
          docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes --credential yes && \
          docker buildx create --name builder-${GITHUB_SHA::8} --driver docker-container --use && \
          docker buildx inspect --bootstrap && \
          docker info && \
          docker buildx inspect && \
      
      - name: Available platforms
        run: docker buildx inspect | grep Platforms

      - name: Build images
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: | 
          docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le \
            --output "type=image,push=false" --cache-to "type=local,dest=/tmp/cache" \
            --tag zabbix/zabbbix-agent:latest \
            --file ./agent/alpine/Dockerfile ./agent/alpine

      - name: Inspect images
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker buildx imagetools inspect zabbix/zabbbix-agent:latest
