# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 5.0 branch
on:
  push:
    branches:
      - trunk
      - dotneft-patch-1
    paths-ignore:
      - '.env*'
      - 'docker-compose*.yaml'
      - '*/rhel/*'
  pull_request:
    branches:
      - trunk   

jobs:
  build:
    strategy:
      fail-fast: false  
      matrix:
        build: 
          - agent
        os:
         - alpine
        exclude:
          - os: centos
            build: agent2
          - os: ubuntu
            build: agent2


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                                      

      - name: Install buildx
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          echo "${{ on.push.branches }}"
