# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 5.0 branch
on:
  push:
    branches:
      - trunk
      - dotneft-patch-1
    paths-ignore:
      - '.env*'
      - 'docker-compose*.yaml'
      - '*/rhel/*'
  pull_request:
    branches:
      - trunk   

jobs:
  build:
    env:
      LATEST_BRANCH: "5.0"
      DOCKER_REPOSITORY: "zabbix"
    strategy:
      fail-fast: false  
      matrix:
        build: 
          - agent
        os:
         - alpine
        exclude:
          - os: centos
            build: agent2
          - os: ubuntu
            build: agent2


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                                                                      

      - name: test
        run: |
          env
          echo "${{ github.ref }}"
          echo "${LATEST_BRANCH}"
          echo "${{ env.LATEST_BRANCH }}"
          echo "${{ env.DOCKER_REPOSITORY }}"
          echo "${{ github.event_name }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.action }}"
